### ISSUE TITLE
Latest update borked plugin

### ISSUE THREAD

**Issue by mebrett** [omeka/plugin-VraCore#91]
On both branch master and the tag v1.1-rc2, I'm getting an "upgrade the plugin" message when I go to admin/plugins on my install. When I click "upgrade" I get the following error:

```
exception 'BadMethodCallException' with message 'Method named 'findByElementId' does not exist or is not callable.' in /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Omeka/Db/Table.php:83
Stack trace:
#0 /websites/omekadev/home/www/mebrett/Omeka/plugins/VraCore/VraCorePlugin.php(198): Omeka_Db_Table->__call('findByElementId', Array)
#1 /websites/omekadev/home/www/mebrett/Omeka/plugins/VraCore/VraCorePlugin.php(198): Table_ElementText->findByElementId(490)
#2 [internal function]: VraCorePlugin->hookUpgrade(Array)
#3 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Omeka/Plugin/Broker.php(145): call_user_func(Array, Array)
#4 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Omeka/Plugin/Installer.php(99): Omeka_Plugin_Broker->callHook('upgrade', Array, Object(Plugin))
#5 /websites/omekadev/home/www/mebrett/Omeka/application/controllers/PluginsController.php(237): Omeka_Plugin_Installer->upgrade(Object(Plugin))
#6 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Zend/Controller/Action.php(516): PluginsController->upgradeAction()
#7 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('upgradeAction')
#8 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#9 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#10 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#11 /websites/omekadev/home/www/mebrett/Omeka/application/libraries/Omeka/Application.php(77): Zend_Application->run()
#12 /websites/omekadev/home/www/mebrett/Omeka/admin/index.php(28): Omeka_Application->run()
#13 {main}
```

**Comment by patrickmj** [comment]
just pushed up a change that should fix the upgrade

**Comment by mebrett** [comment]
That fixed it.
